
import * as z from 'zod';

export const clientSchema = z.object({
  responsibleProfessional: z.string().optional(),
  group: z.string().optional(),
  name: z.string().min(1, 'Nome é obrigatório'),
  whatsapp: z.string().optional(),
  videoCallLink: z.string().url().optional().or(z.literal('')),
  email: z.string().email().optional().or(z.literal('')),
  cpf: z.string().optional(),
  rg: z.string().optional(),
  cep: z.string().optional(),
  address: z.string().optional(),
  number: z.string().optional(),
  neighborhood: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  complement: z.string().optional(),
  sessionValue: z.string().optional(),
  paymentDay: z.string().optional(),
  sendMonthlyReminder: z.boolean().default(false),
  financialResponsibleName: z.string().optional(),
  financialResponsibleWhatsapp: z.string().optional(),
  financialResponsibleEmail: z.string().email().optional().or(z.literal('')),
  financialResponsibleCpf: z.string().optional(),
  financialResponsibleRg: z.string().optional(),
  emergencyContactName: z.string().optional(),
  emergencyContactWhatsapp: z.string().optional(),
  gender: z.string().optional(),
  birthDate: z.string().optional(),
  nationality: z.string().optional(),
  education: z.string().optional(),
  profession: z.string().optional(),
  referral: z.string().optional(),
  maritalStatus: z.string().optional(),
  observations: z.string().optional(),
  activateSessionReminder: z.boolean().default(false),
  activeRegistration: z.boolean().default(true),
});

export type ClientFormData = z.infer<typeof clientSchema>;
