// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asxwlqqzdapfdbfaqbfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeHdscXF6ZGFwZmRiZmFxYmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjI3NjMsImV4cCI6MjA2NDY5ODc2M30.HJ_hD8D-WRYblUUsqXtLEhi5IUX_OXGdszrds4H1Bg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);