// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnefjtjtlcsbiiykwqak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZWZqdGp0bGNzYmlpeWt3cWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjcyMzMsImV4cCI6MjA2Mzk0MzIzM30.BfzIsnumL2m1dC68ZhPwhVVwEPtSL0CyGF9wvzHvAP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);